class Categories {
  static List<Map<String, dynamic>> categories = [
    {
      "id": 4,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Fashion",
      "slug": "fashion",
      "lft": 1,
      "rght": 38,
      "tree_id": 1,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 13,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Women's Fashion",
          "slug": "women-fashion",
          "lft": 2,
          "rght": 13,
          "tree_id": 1,
          "level": 1,
          "parent": 4
        },
        {
          "id": 14,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Men's Fashion",
          "slug": "men-fashion",
          "lft": 14,
          "rght": 21,
          "tree_id": 1,
          "level": 1,
          "parent": 4
        },
        {
          "id": 15,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Girl's Fashion",
          "slug": "girl-fashion",
          "lft": 22,
          "rght": 29,
          "tree_id": 1,
          "level": 1,
          "parent": 4
        },
        {
          "id": 16,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Boy's Fashion",
          "slug": "boy-fashion",
          "lft": 30,
          "rght": 37,
          "tree_id": 1,
          "level": 1,
          "parent": 4
        }
      ]
    },
    {
      "id": 5,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Electronics",
      "slug": "electronics",
      "lft": 1,
      "rght": 12,
      "tree_id": 2,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 17,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Camera",
          "slug": "camera",
          "lft": 2,
          "rght": 3,
          "tree_id": 2,
          "level": 1,
          "parent": 5
        },
        {
          "id": 18,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Car & Vehicle Electronics",
          "slug": "car-vehicle-electronics",
          "lft": 4,
          "rght": 5,
          "tree_id": 2,
          "level": 1,
          "parent": 5
        },
        {
          "id": 19,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Office Electronics",
          "slug": "office-electronics",
          "lft": 6,
          "rght": 7,
          "tree_id": 2,
          "level": 1,
          "parent": 5
        },
        {
          "id": 20,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Security & Surveillance",
          "slug": "security-surveillance",
          "lft": 8,
          "rght": 9,
          "tree_id": 2,
          "level": 1,
          "parent": 5
        },
        {
          "id": 21,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Wearable Technology",
          "slug": "wearable-technology",
          "lft": 10,
          "rght": 11,
          "tree_id": 2,
          "level": 1,
          "parent": 5
        }
      ]
    },
    {
      "id": 6,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Mobiles",
      "slug": "mobiles",
      "lft": 1,
      "rght": 2,
      "tree_id": 3,
      "level": 0,
      "parent": null,
      "sub_category": []
    },
    {
      "id": 7,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Computers",
      "slug": "computers",
      "lft": 1,
      "rght": 2,
      "tree_id": 4,
      "level": 0,
      "parent": null,
      "sub_category": []
    },
    {
      "id": 8,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Home and Decor",
      "slug": "home-decor",
      "lft": 1,
      "rght": 16,
      "tree_id": 5,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 22,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Kitchen & Dining",
          "slug": "kitchen-dining",
          "lft": 2,
          "rght": 3,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 23,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Furniture",
          "slug": "furniture",
          "lft": 4,
          "rght": 5,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 24,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Wall Art",
          "slug": "wall-art",
          "lft": 6,
          "rght": 7,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 25,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Seasonal Decor",
          "slug": "seasonal-decor",
          "lft": 8,
          "rght": 9,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 26,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Iron & Steamers",
          "slug": "iron-steamer",
          "lft": 10,
          "rght": 11,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 27,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Bedding",
          "slug": "bedding",
          "lft": 12,
          "rght": 13,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        },
        {
          "id": 28,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Storage & Organization",
          "slug": "storage-organization",
          "lft": 14,
          "rght": 15,
          "tree_id": 5,
          "level": 1,
          "parent": 8
        }
      ]
    },
    {
      "id": 9,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Gardening Inputs",
      "slug": "gardening-inputs",
      "lft": 1,
      "rght": 16,
      "tree_id": 6,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 29,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Garden Tools",
          "slug": "garden-tools",
          "lft": 2,
          "rght": 5,
          "tree_id": 6,
          "level": 1,
          "parent": 9
        },
        {
          "id": 31,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Seeds",
          "slug": "seeds",
          "lft": 6,
          "rght": 13,
          "tree_id": 6,
          "level": 1,
          "parent": 9
        },
        {
          "id": 35,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Watering Can",
          "slug": "watering-can",
          "lft": 14,
          "rght": 15,
          "tree_id": 6,
          "level": 1,
          "parent": 9
        }
      ]
    },
    {
      "id": 10,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Books",
      "slug": "books",
      "lft": 1,
      "rght": 2,
      "tree_id": 7,
      "level": 0,
      "parent": null,
      "sub_category": []
    },
    {
      "id": 11,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Beauty and Personal Care",
      "slug": "beauty-and-personal-care",
      "lft": 1,
      "rght": 12,
      "tree_id": 8,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 36,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Makeup",
          "slug": "makeup",
          "lft": 2,
          "rght": 3,
          "tree_id": 8,
          "level": 1,
          "parent": 11
        },
        {
          "id": 37,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Skin Care",
          "slug": "skin-care",
          "lft": 4,
          "rght": 5,
          "tree_id": 8,
          "level": 1,
          "parent": 11
        },
        {
          "id": 38,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Hair Care",
          "slug": "hair-care",
          "lft": 6,
          "rght": 7,
          "tree_id": 8,
          "level": 1,
          "parent": 11
        },
        {
          "id": 39,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Foot, Hand & Nail Care",
          "slug": "foot-hand-nail-care",
          "lft": 8,
          "rght": 9,
          "tree_id": 8,
          "level": 1,
          "parent": 11
        },
        {
          "id": 40,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Personal Care",
          "slug": "personal-care",
          "lft": 10,
          "rght": 11,
          "tree_id": 8,
          "level": 1,
          "parent": 11
        }
      ]
    },
    {
      "id": 12,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Toys and Games",
      "slug": "toys-games",
      "lft": 1,
      "rght": 2,
      "tree_id": 9,
      "level": 0,
      "parent": null,
      "sub_category": []
    },
    {
      "id": 61,
      "icon": null,
      "image": null,
      "is_active": true,
      "name": "Commercial Products",
      "slug": "commercial-products",
      "lft": 1,
      "rght": 12,
      "tree_id": 11,
      "level": 0,
      "parent": null,
      "sub_category": [
        {
          "id": 56,
          "icon": null,
          "image": null,
          "is_active": true,
          "name": "Industrial Inks",
          "slug": "industrial-inks",
          "lft": 2,
          "rght": 11,
          "tree_id": 11,
          "level": 1,
          "parent": 61
        }
      ]
    }
  ];
}
